#server configuration
server:
  servlet:
    context-path: /api
  port: 2233

#database configuration
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/nidinfo
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 132311

#mybatis configuration
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hust.addrgeneration.beans